# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 86e40c6d60a55d4cce2b6a1deb8fc559177207ae2876f59a2e4f66f3311c12d284d361004dadc3c4a819f80d065831bc388e553250315600eea9c266cf659e38

test:
  secret_key_base: 789c965092118f8752c20b444ce3e568d0f1420159bcf31c57e47720936efde0583b2282df330da52880441a9e952bf89669d1155b7b2c796e91b545bf27a8b9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
